     
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        prefer-ip-address: true
server:
    port: 8085
spring:
    application:
        name: API-GATEWAY

    cloud:
        gateway:
            routes:
              - id: userservic
                uri: http://localhost:8086
                predicates:
                  - Path=/users/**
              
              - id: HOTELSERVICE
                uri: http://localhost:8082
                predicates:
                  - Path=/hotels/**                
                
              - id: RATINGSERVICE
                uri: http://localhost:8083
                predicates:
                  - Path=/ratings/**                
                     
            
                  
    main:
        web-application-type: reactive  
